server:
  port: 8091
  context-path: /easyid


mybatis:
  mapper-locations: classpath:com/wuyu/easyid/server/dao/mapper/*.xml
  type-aliases-package: com.wuyu.easyid.server.model
  configuration:
    mapUnderscoreToCamelCase: true


spring:
  datasource:
    url: jdbc:mysql://mysql.dev.tanzk.com:3306/crm_follow?useUnicode=true&characterEncoding=utf8&autoReconnect=true
    username: app_crm_follow
    password: f2e1c23423423dfs#sq
    driver-class-name:  com.mysql.jdbc.Driver
    initial-size: 1
    max-active: 500
    min-idle: 1
    max-wait: 60000
    pool-prepared-statements: true
    max-pool-prepared-statement-per-connection-size:  20
    validation-query: select 'x'
    test-on-borrow: false
    test-while-idle: true
    test-on-return: false
    time-between-eviction-runs-millis:  60000
    min-evictable-idle-time-millis: 30000
    filters:  config
